// Automatically generated by generate_extend_inittab.py
#include "Python.h"

PyMODINIT_FUNC initcolor(void);
PyMODINIT_FUNC initdisplay(void);
PyMODINIT_FUNC initdraw(void);
PyMODINIT_FUNC initerror(void);
PyMODINIT_FUNC initevent(void);
PyMODINIT_FUNC initfont(void);
PyMODINIT_FUNC initgfxdraw(void);
PyMODINIT_FUNC initimage(void);
PyMODINIT_FUNC initjoystick(void);
PyMODINIT_FUNC initkey(void);
PyMODINIT_FUNC initlocals(void);
PyMODINIT_FUNC initmouse(void);
PyMODINIT_FUNC initrect(void);
PyMODINIT_FUNC initrender(void);
PyMODINIT_FUNC initrwobject(void);
PyMODINIT_FUNC initscrap(void);
PyMODINIT_FUNC initsurface(void);
PyMODINIT_FUNC inittime(void);
PyMODINIT_FUNC inittransform(void);
PyMODINIT_FUNC initpyobjus(void);

void renios_extend_inittab(void) {
    PyImport_AppendInittab("pygame_sdl2.color", initcolor);
    PyImport_AppendInittab("pygame_sdl2.display", initdisplay);
    PyImport_AppendInittab("pygame_sdl2.draw", initdraw);
    PyImport_AppendInittab("pygame_sdl2.error", initerror);
    PyImport_AppendInittab("pygame_sdl2.event", initevent);
    PyImport_AppendInittab("pygame_sdl2.font", initfont);
    PyImport_AppendInittab("pygame_sdl2.gfxdraw", initgfxdraw);
    PyImport_AppendInittab("pygame_sdl2.image", initimage);
    PyImport_AppendInittab("pygame_sdl2.joystick", initjoystick);
    PyImport_AppendInittab("pygame_sdl2.key", initkey);
    PyImport_AppendInittab("pygame_sdl2.locals", initlocals);
    PyImport_AppendInittab("pygame_sdl2.mouse", initmouse);
    PyImport_AppendInittab("pygame_sdl2.rect", initrect);
    PyImport_AppendInittab("pygame_sdl2.render", initrender);
    PyImport_AppendInittab("pygame_sdl2.rwobject", initrwobject);
    PyImport_AppendInittab("pygame_sdl2.scrap", initscrap);
    PyImport_AppendInittab("pygame_sdl2.surface", initsurface);
    PyImport_AppendInittab("pygame_sdl2.time", inittime);
    PyImport_AppendInittab("pygame_sdl2.transform", inittransform);
    PyImport_AppendInittab("pyobjus.pyobjus", initpyobjus);
}
